/*
 * Generated by MTK Easy PinMux Tool Version 2.3.0 for 2523. Copyright MediaTek Inc. (C) 2015.
 * 2017-09-02 11:22:17:0268
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

const unsigned char BSP_GPS_EINT = 10;
const unsigned char BSP_CTP_EINT = 13;
const unsigned char HAL_MSDC_EINT = 19;
const unsigned char HAL_ACCDET_EINT = 0xff;
const unsigned char BSP_GNSS_EINT = 0xff;
const unsigned char BSP_WIFI_EINT = 0xff;
const unsigned char MODEM_EXCEPTION_EINT = 0xff;
const unsigned char MODEM_WAKEUP_EINT = 0xff;
const unsigned char BSP_EINTKEY0_EINT = 0xff;
const unsigned char BSP_EINTKEY1_EINT = 0xff;
const unsigned char BSP_EINTKEY2_EINT = 0xff;



